version : '3'

services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres_exo

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080" #port host:port container